name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change Directory to LittleLemonApp
        run: cd LittleLemonApp

      - name: List Directory Contents Inside LittleLemonApp
        run: ls -R

      - name: Build and Analyze
        run: |
          project_path="LittleLemonApp.xcodeproj"
          xcodebuild clean build analyze -project "$project_path" -scheme "LittleLemonApp" | xcpretty && exit ${PIPESTATUS[0]}
